export const architecturePage = {
  badges: ["🏆 Proprietary · Production-Proven", "Enterprise AI Infrastructure"],
  eyebrow: "Sovereign Architecture",
  title1: "Sovereign",
  title2: "Architecture",
  body: "The 7-layer Sovereign Computing Architecture (SCA) powers everything we build. It provides the immutable governance, memory, and automation infrastructure underneath our Commander AI pipeline.",
  toc: ["📐 Architecture Diagram", "💡 The Big Truth", "🥞 7 Layers Explained", "🚀 Real-World Cases", "⚖️ Side By Side"],
  domainPacks: {
    heading: "Plug Any Domain Pack Into SCA — Nothing Else Changes",
    packs: ["HealthPack 🏥", "SchoolPack 🎓", "ERPPack 🏢", "CRMPack 💼", "ECommercePack 🛒", "CustomClientPack ⚙"],
    inputsHeading: "Any Inputs",
    inputs: [
      { icon: "📋", label: "Forms & Screens", detail: "Patient reg, attendance, PO, lead entry" },
      { icon: "📄", label: "PDF Documents", detail: "Lab reports, contracts, prescriptions" },
      { icon: "📧", label: "Emails", detail: "Supplier prices, customer queries" },
      { icon: "🎤", label: "Voice Notes", detail: "Doctor dictations, field notes" },
      { icon: "📊", label: "Excel / CSV", detail: "SAP exports, bulk data" },
      { icon: "🔗", label: "API Webhooks", detail: "Payments, alerts, integrations" },
      { icon: "📸", label: "Images / Scans", detail: "Handwritten forms, OCR" },
    ],
    runtimeLabel: "→ Into SCA Runtime",
  },
  layers: [
    {
      id: "L9",
      name: "COMMANDER",
      role: "INTELLIGENCE",
      icon: "♛",
      desc: "Reads signals → Generates directives → Routes agents → Reviews output → Never executes",
      modules: ["DirectiveEngine", "AgentRouter", "ReviewGate", "PromptRewriter", "ScriptDeploy"],
      footer: "Claude Opus · Prompt Cached · ~₹3/directive",
      commander: true,
    },
    {
      id: "L8",
      name: "MEMORY LAYER",
      role: "MEMORY",
      icon: "🧠",
      desc: "Episodic · Semantic · Operational — Enterprise knowledge asset with retention policies",
      modules: ["EpisodicMemory", "SemanticMemory", "TrustScore", "RetentionPolicy"],
      footer: "pgvector · Embeddings · VectorDB",
    },
    {
      id: "L7",
      name: "OMNIPROCESSOR",
      role: "PROCESSING",
      icon: "⬡",
      desc: "Chaos → Structure · Any format → Typed domain object · 5-tier local-first routing",
      modules: ["T0: dedup ₹0", "T1: Python ₹0", "T2: Ollama ₹0", "T3: Haiku ₹0.05", "T4: Sonnet ₹0.80"],
      footer: "96% COST REDUCTION vs GPT-4 only",
    },
    {
      id: "L6",
      name: "NERVE",
      role: "AUTOMATION",
      icon: "⚡",
      desc: "Local automation OS · Replaces Zapier at ₹0/month · File watchers · Schedulers · Health monitors",
      modules: ["ServiceA: Ingest", "ServiceB: Post", "ServiceC: Health", "NerveJobLog"],
      footer: "₹0/month vs ₹15K+ Zapier cost",
    },
    {
      id: "L5",
      name: "OBSERVABILITY",
      role: "VISIBILITY",
      icon: "L5",
      desc: "Nothing executes invisibly · Logs · Metrics · Traces · Cost tracking · Agent performance",
      modules: ["OpenTelemetry", "Grafana", "CostTracker", "AgentMetrics", "SovereignLog"],
      footer: "Real-time · All layers · All tenants",
    },
    {
      id: "L4",
      name: "AGENT REGISTRY",
      role: "GOVERNANCE",
      icon: "🤖",
      desc: "No unregistered agent executes · Identity · Version · Permissions · Risk class · Audit trail",
      modules: ["AgentManifest", "AgentLifecycle", "Unregistered → 403", "MCP Tools"],
      footer: "403 Forbidden if not registered",
    },
    {
      id: "L3",
      name: "WORKFLOW RUNTIME",
      role: "WORKFLOW",
      icon: "🔄",
      desc: "Every business process · Durable execution · Human approvals · State persistence · Auto-recovery",
      modules: ["PO Approval", "Patient Discharge", "Deal Stages", "Admission Flow"],
      footer: "Stateless → Temporal Phase 2",
    },
    {
      id: "L2",
      name: "IRON DOME GOVERNANCE",
      role: "CRITICAL",
      icon: "🛡",
      desc: "Every request intercepted · Zero bypass · Cost control · PII redaction · Audit trail · RBAC · Tenant isolation",
      modules: ["IronDomeBehavior", "PIIFilter", "CostCircuitBreaker", "AuditLogger", "RBACBehavior", "TenantFilter"],
      footer: "NO BYPASS EVER · COMPLIANT",
      critical: true,
    },
    {
      id: "L1",
      name: "DOMAIN RUNTIME",
      role: "DOMAIN",
      icon: "📦",
      desc: "Domain Pack loader · Plugin isolation · Vertical slice features · IDomainPack contracts",
      modules: ["HospitalPack", "SchoolPack", "ERPPack", "CRMPack", "+Any Domain"],
      footer: "Plugin Isolated · Hot-swap",
    },
    {
      id: "L0",
      name: "SOVEREIGN KERNEL",
      role: "FOUNDATION",
      icon: "⚙",
      desc: "Bootstrap · Configuration · Plugin loading · Multi-tenant provisioning · Feature flags · Licensing",
      modules: ["IPluginLoader", "TenantProvisioner", "FeatureFlags", "ConfigManager"],
      footer: ".NET 10 · Native AOT · ms startup",
    },
  ],
  outputsHeading: "Intelligent Outputs",
  outputs: [
    { icon: "📱", label: "WhatsApp Alerts", detail: "Readmission risk, attendance, deal follow-up" },
    { icon: "📊", label: "Smart Dashboards", detail: "Real-time KPIs, predictions, health scores" },
    { icon: "📋", label: "Auto Reports", detail: "Daily digest, weekly parent report, CFO P&L" },
    { icon: "🤖", label: "Agent Actions", detail: "Insurance filing, forecast generation, alerts" },
    { icon: "🔮", label: "Forecasts", detail: "30/60/90-day predictions per domain" },
    { icon: "📧", label: "Email Campaigns", detail: "Sunday Sanctuary, parent reports, invoices" },
    { icon: "📁", label: "Audit Reports", detail: "HIPAA, SOX, GDPR — compliance ready" },
  ],
  outputsFooter: "← Actioned by SCA",
  replacesHeading: "SCA Replaces All of These — In One Integrated Platform",
  replaces: [
    "Zapier / n8n (₹15K+/mo)",
    "Separate audit system",
    "Manual governance policies",
    "Custom LLM wrappers",
    "Separate workflow engine",
    "Basic chatbots",
    "Ungoverned AI agents",
    "Domain-specific rebuilds",
  ],
  stats: [
    { value: "10", label: "Architecture Layers" },
    { value: "96%", label: "AI Cost Reduction" },
    { value: "∞", label: "Domains Supported" },
    { value: "100%", label: "Requests Governed" },
    { value: "8 Wks", label: "To Production" },
    { value: "₹0", label: "Automation Cost" },
    { value: "3 Cr+", label: "Annual Revenue Potential" },
  ],
  legend: ["Intelligence", "Governance", "Domain Pack", "Local / Free", "Agent Registry", "Workflow", "Visibility", "Memory"],
  cta: "Want SCA & Commander Architecture deployed for your business?",
  ctaButton: "🚀 License Sovereign Architecture",
};
