export type Project = {
  id: string;
  icon: string;
  badge: string;
  year?: string;
  title: string;
  body: string;
  tags: string[];
  cta?: string;
  categories: string[];
};

export const workPage = {
  eyebrow: "Selected Work",
  title: "Products We've Shipped",
  body: "Real products, real clients, real production environments — across the USA, Europe and India. No mockups. No slide decks. Shipped code.",
  filters: ["All Projects", "AI & Agents", "SaaS Platforms", "HealthTech", "Mobility & EduTech"],
};

export const projects: Project[] = [
  {
    id: "commander-architecture",
    icon: "🤖",
    badge: "AI · Multi-Agent · Proprietary",
    year: "2024–2025",
    title: "Commander Architecture — Autonomous Agent Pipeline",
    body: "5-agent autonomous content pipeline. Claude Opus as Supreme Commander reads market signals → generates directives.json → Qwen local agents execute at ~$0.001/task. ~90% prompt cache hit rate. 40–70% overall AI cost reduction vs pure cloud.",
    tags: ["Claude Opus", "Qwen 3:32B", "Ollama", "n8n", "Autonomous"],
    categories: ["AI & Agents"],
  },
  {
    id: "multi-t-ecomm",
    icon: "🛒",
    badge: "E-Commerce · AI · SaaS",
    year: "2025–2026",
    title: "Multi-T-Ecomm — AI-Powered Multi-Tenant E-Commerce",
    body: "An AI-powered multi-tenant e-commerce platform with an intelligent shopping assistant supporting voice, chat, and automated product discovery using LLM reasoning, RAG, and real-time API tools.",
    tags: ["Next.js", "FastAPI", "PostgreSQL", "Prisma ORM", "LangChain", "OpenRouter", "Whisper"],
    categories: ["SaaS Platforms", "AI & Agents"],
  },
  {
    id: "content-automation",
    icon: "🤖",
    badge: "RPA · AI · Multi-Channel",
    year: "2025–2026",
    title: "Content Automation Studio — RPA & AI Publishing Suite",
    body: "Enterprise-grade automated content creation, scheduling, rendering, and multi-platform publishing system using AI agent orchestration and Robotic Process Automation (RPA).",
    tags: ["React", "Next.js", "Tailwind CSS", "FastAPI", "Puppeteer", "SQLite", "Notion API", "OpenAI API", "Stable Diffusion"],
    categories: ["AI & Agents", "SaaS Platforms"],
  },
  {
    id: "helpinghand",
    icon: "🤝",
    badge: "SaaS · 3D Canvas · Real-time",
    year: "2025–2026",
    title: "HelpingHand Enterprise — Next-Gen Service Marketplace",
    body: "A comprehensive, multi-role on-demand services marketplace connecting customers, service providers, and administrators with real-time tracking, chat, and automated financial settlements.",
    tags: ["Angular", "TypeScript", "Tailwind CSS", "Node.js", "Express.js", "Socket.io", "Stripe API", "MongoDB", "Redis"],
    categories: ["SaaS Platforms"],
  },
  {
    id: "hivegpt",
    icon: "☁️",
    badge: "SaaS · AI Campaigns · USA",
    year: "2022–2023",
    title: "HiveGPT — AI Campaign Intelligence Platform",
    body: "Generative AI platform that automates marketing workflows using an agent-based system to improve efficiency, reduce workload, and enable data-driven decision making.",
    tags: ["Angular 10+", "React 16+", "TypeScript", "ASP.NET Core", "Python", "Generative AI", "AI Agents"],
    categories: ["AI & Agents", "SaaS Platforms"],
  },
  {
    id: "social27",
    icon: "🎪",
    badge: "Enterprise · Events SaaS · Seattle",
    year: "2020–2022",
    title: "Social27 — Enterprise Virtual Events Platform",
    body: "AI-powered virtual and hybrid events platform enabling businesses to create, manage, and scale engaging webinars and online events with global reach.",
    tags: ["Angular 10+", "React 16+", "TypeScript", "ASP.NET Core", "Node.js", "MySQL", "Microsoft Azure"],
    categories: ["SaaS Platforms"],
  },
  {
    id: "contacthub",
    icon: "📱",
    badge: "Mobile · CRM · SaaS",
    year: "2023",
    title: "ContactHub — Unified CRM & Communication Platform",
    body: "Enterprise contact management, unified chat inbox, automated inquiry workflows, and email deliverability monitoring. Cross-platform React Native client paired with a .NET Core admin console.",
    tags: ["React Native", "Expo", ".NET Core API", "SQL Server", "SMTP Monitoring"],
    categories: ["Mobility & EduTech"],
  },
  {
    id: "hospital-os",
    icon: "🏥",
    badge: "HealthTech · HIPAA",
    year: "2022–2024",
    title: "Hospital OS — Full Hospital Management Platform",
    body: "Modern full-stack Hospital Management System to manage admissions, wards, beds, users, roles, and doctor scheduling with real-time insights.",
    tags: ["React 16+", "Tailwind CSS", "Node.js", "Express.js", "MongoDB", "JWT"],
    categories: ["HealthTech"],
  },
  {
    id: "intelligent-wms",
    icon: "📦",
    badge: "WMS · RFID · AI",
    year: "2022–2024",
    title: "Intelligent WMS — Inventory & Warehouse SaaS",
    body: "Enterprise-grade inventory and warehouse management web application with a premium glassmorphism UI, real-time stock insights, and rich animations.",
    tags: ["Angular 10+", "TypeScript", "RxJS", "Tailwind CSS", "GSAP", "Lottie Animations"],
    categories: ["SaaS Platforms"],
  },
  {
    id: "school-os",
    icon: "🎓",
    badge: "EduTech · AI",
    year: "2023–2024",
    title: "School OS — Adaptive Education Platform",
    body: "All-in-one digital platform to manage academics, administration, fees, and communication.",
    tags: ["Angular 10+", "TypeScript", "Bootstrap", "Chart.js", "ApexCharts", "ASP.NET Core", ".NET 6+", "SignalR", "SQL Server"],
    categories: ["Mobility & EduTech"],
  },
  {
    id: "vector-rag-ai",
    icon: "🤖",
    badge: "AI · RAG · Search",
    year: "2024",
    title: "Vector RAG AI — Enterprise Knowledge Base",
    body: "Advanced AI chatbot using vector embeddings and semantic search for context-aware knowledge retrieval.",
    tags: ["Python", "FastAPI", "React", "Next.js", "Tailwind CSS", "LangChain", "LlamaIndex", "FAISS", "Pinecone", "Weaviate", "pgvector"],
    categories: ["AI & Agents"],
  },
  {
    id: "healthsync-phr",
    icon: "🏥",
    badge: "HealthTech · Patient PHR",
    year: "2024",
    title: "HealthSync PHR — Patient Personal Health Record",
    body: "Patient management and telemedicine platform for healthcare providers.",
    tags: ["React Native", "TypeScript", "Node.js", "GraphQL", "Apollo", "MongoDB", "Elasticsearch"],
    categories: ["HealthTech"],
  },
  {
    id: "hope-clinic",
    icon: "🏥",
    badge: "HealthTech · Clinic CRM",
    year: "2023",
    title: "Hope Clinic — Mental Wellness & Clinical CRM",
    body: "HIPAA-aware clinic management system for patient onboarding, smart scheduling, medical billing, and secure therapist communication.",
    tags: ["React", "Node.js", "MongoDB", "Twilio Video", "HIPAA-Aware"],
    categories: ["HealthTech"],
  },
  {
    id: "ielts-ai",
    icon: "🧠",
    badge: "EduTech · AI Assessment",
    year: "2024",
    title: "IELTS AI — Adaptive Assessment Platform",
    body: "Adaptive IELTS testing platform using AI for dynamic question difficulty, real-time grading, cognitive analysis, and personalised performance insights.",
    tags: ["Next.js", "Node.js", "Claude API", "Tailwind CSS", "Analytics"],
    categories: ["Mobility & EduTech", "AI & Agents"],
  },
  {
    id: "ai-yoga-instructor",
    icon: "🏥",
    badge: "HealthTech · Computer Vision",
    year: "2024",
    title: "AI Yoga Instructor — Real-time Pose Estimation",
    body: "AI-powered yoga instruction platform offering personalized routines, guided sessions, and progress tracking across web and mobile experiences.",
    tags: ["Angular 10+", "TypeScript", "Angular Material", "Node.js", "Express.js", "React Native", "Expo", "MongoDB", "OpenAI"],
    categories: ["HealthTech", "Mobility & EduTech"],
  },
  {
    id: "enterprise-mern-saas",
    icon: "🏬",
    badge: "SaaS · Boilerplate",
    year: "2022–2023",
    title: "Enterprise MERN SaaS Platform",
    body: "High-performance SaaS Admin Dashboard providing secure authentication, role-based access, analytics, and system management for modern web applications.",
    tags: ["React 16+", "Vite", "Tailwind CSS", "Framer Motion", "Node.js", "Express.js", "MongoDB", "JWT"],
    categories: ["SaaS Platforms"],
  },
];
